[tool.uv.workspace]
members = [
  "agents/supervisor",
  "agents/ingestion",
  "services/orchestrator",
  "services/api",
  "shared/core"
]

[tool.uv]
dev-dependencies = [
  "pytest>=8.3",
  "ruff>=0.6",
  "mypy>=1.10"
]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "B"]

[tool.pytest.ini_options]
addopts = "-q"
python_files = ["test_*.py", "*_test.py"]
